export const ACT_LOAD_COCKTAILS = "ACT_LOAD_COCKTAILS";
export const SELECTED_COCKTAIL = "SELECTED_COCKTAIL";
export const CHANGE_APP_PROPS = "CHANGE_APP_PROPS";
export const LOAD_DETAILS = "LOAD_DETAILS";